"""Updated Article Model with temp

Revision ID: 1e88d4252bf6
Revises: 9df5e4c966c2
Create Date: 2024-06-19 11:06:42.714710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e88d4252bf6'
down_revision: Union[str, None] = '9df5e4c966c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('temp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'temp')
    # ### end Alembic commands ###
